# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "Futu"
license = "MIT"
licenselink = "https://github.com/masakichi/futu/blob/master/LICENSE"
description = ""
homepage = "https://github.com/masakichi/futu"
tags = []
features = []
min_version = "0.86.0"

[author]
  name = "Yuanji"
  homepage = "https://blog.gimo.me"
